name: ci

on:
  push:
    branches: [main, dev, release, prod]
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: install
        run: npm install

      - name: lint (if there is one)
        run: |
          if grep -q "\"lint\":" package.json; then
            npm run lint
          else
            echo "no lint script"
          fi

      - name: test (if there is one)
        run: |
          if grep -q "\"test\":" package.json; then
            npm test
          else
            echo "no tests"
          fi

      - name: build (if there is one)
        run: |
