name: build-docker

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: make image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/myapp:latest .

      - name: send image
        run: docker push ghcr.io/${{ github.repository_owner }}/myapp:latest

      - name: done
        run: echo "image done"
